### ISSUE TITLE
Use this plugin for conversation shortcut

### ISSUE THREAD

**Issue by PapyElGringo** [DevsOnFlutter/flutter_shortcuts#11]
Is it possible to use this plugin to achieve Android conversation shortcut?

https://developer.android.com/guide/topics/ui/conversations#api-shortcuts

I parsed quickly the source code but I haven't seen anything related to long lived shortcut so I was wondering if it's possible.

Thanks in advance !

**Comment by divshekhar** [comment]
Thank you @PapyElGringo for suggesting this feature, conversation shortcuts have been included in v1.3.0 (PR #12). Closing the issue, feel free to reopen if you face any issues.

**Comment by PapyElGringo** [comment]
Awesome thanks 👍
